# origin Travis CI form https://github.com/JonathanPorta/ci-build

language: objective-c
osx_image: xcode7.3
rvm:
- 2.1.2

env:
  matrix:
    - UNITY_VERSION=5.6

before_install:
- chmod -R +x ./Scripts
install:
- travis_wait 50 ./Scripts/install.sh
script:
- ./Scripts/build.sh
